//HintName: SansEnumDefinition.json.cs
#if COMPILE_JSON
/*
 * Auto generated by XrmFramework 2.0
 * Do not edit directly this file
 */
const sansEnumDefinition = {
    LogicalName: "sansEnum",
    SchemaName: "SansEnum",
    CollectionName: "sansEnums",
    LogicalCollectionName: "sansEnums",
    PrimaryIdAttribute: "accountid",
    PrimaryNameAttribute: "name",
    Columns: {
        AccountCategoryCode: "accountcategorycode",
        Id: "accountid",
        AccountNumber: "accountnumber",
        Address1_County: "address1_county",
        Address1_Latitude: "address1_latitude",
        Address1_Line3: "address1_line3",
        Address1_PostalCode: "address1_postalcode",
        Address1_StateOrProvince: "address1_stateorprovince",
        Address2_FreightTermsCode: "address2_freighttermscode",
        Name: "name"
    }
};
#endif
