//HintName: ParticulierDefinition.cs
#if COMPILE_JSON
/*
 * Auto generated by XrmFramework 2.0
 * Do not edit directly this file
 */
const ParticulierDefinition = {
    LogicalName: "ftp_particulier",
    SchemaName: "Particulier",
    CollectionName: "ftp_particuliers",
    LogicalCollectionName: "ftp_particuliers",
    PrimaryIdAttribute: "ftp_particulierid",
    PrimaryNameAttribute: "ftp_name",
    Columns: {
        Budgetparmois: "ftp_budgetparmois",
        Name: "ftp_name",
        Id: "ftp_particulierid"
    },
    Enums: {
        ParticulierState: {
            Actif: 0,
            Inactif: 1
        },
        ParticulierStatus: {
            Actif: 1,
            Inactif: 2
        }
    }
};
#endif
