//HintName: OptionSetDefinition.json.cs
#if COMPILE_JSON
/*
 * Auto generated by XrmFramework 2.0
 * Do not edit directly this file
 */
const globalEnumsDefinition = {
    LogicalName: "globalEnums",
    SchemaName: "OptionSet",
    CollectionName: "",
    LogicalCollectionName: "",
    PrimaryIdAttribute: "",
    PrimaryNameAttribute: "",
    Enums: {
        SynapseLinkProfileEntityType: {
            Requested: 0
        },
        SynapseLinkScheduleType: {
            Snapshot: 0,
            Incrementalupdate: 1
        }
    }
};
#endif
