//HintName: SansColSansEnumDefinition.json.cs
#if COMPILE_JSON
/*
 * Auto generated by XrmFramework 2.0
 * Do not edit directly this file
 */
const sansColSansEnumDefinition = {
    LogicalName: "sansColSansEnum",
    SchemaName: "SansColSansEnum",
    CollectionName: "sansColSansEnums",
    LogicalCollectionName: "sansColSansEnums",
    PrimaryIdAttribute: "",
    PrimaryNameAttribute: ""
};
#endif
