/*
 * Auto generated by XrmFramework 2.0
 * Do not edit directly this file
 */
const ftp_contratdelocationDefinition = {
    LogicalName: "ftp_contratdelocation",
    SchemaName: "Contratdelocation",
    CollectionName: "ftp_contratdelocations",
    LogicalCollectionName: "ftp_contratdelocations",
    PrimaryIdAttribute: "ftp_contratdelocationid",
    PrimaryNameAttribute: "ftp_name",
    Columns: {
        Agent: "ftp_agent",
        Id: "ftp_contratdelocationid",
        Locataire: "ftp_locataire",
        Loyer: "ftp_loyer",
        Name: "ftp_name"
    },
    Enums: {
        ContratdelocationState: {
            Actif: 0,
            Inactif: 1
        },
        ContratdelocationStatus: {
            Actif: 1,
            Inactif: 2
        }
    }
};